//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO1O_1K_MATH.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapters
    {
        public int ID_Chapter { get; set; }
        public string Chapter { get; set; }
        public Nullable<int> ID_theme { get; set; }
        public string Numeration { get; set; }
    
        public virtual Themes Themes { get; set; }
    }
}
